CREATE SCHEMA IF NOT EXISTS PROJECT;

CREATE TABLE PROJECT.PROJECT (
    id SERIAL NOT NULL,
    name VARCHAR(30) NOT NULL,
    CONSTRAINT pk_PROJECT primary key (id)
);

INSERT INTO PROJECT.PROJECT (name)
VALUES
    ('営業支援ツール')
;
