CREATE SCHEMA IF NOT EXISTS PROJECT;

CREATE SEQUENCE PROJECT.PROJECT_SEQUENCE
    INCREMENT BY 1;

CREATE TABLE PROJECT.PROJECT (
    id BIGINT NOT NULL,
    name VARCHAR(30) NOT NULL,
    CONSTRAINT pk_PROJECT primary key (id)
);

INSERT INTO PROJECT.PROJECT (id, name)
VALUES
    (nextval('PROJECT.PROJECT_SEQUENCE'), '営業支援ツール')
;
